version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: rf-mysql
    restart: always
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: read-fast
    volumes:
      - rf-mysql-data:/var/lib/mysql
      - ./mysql/init/master:/docker-entrypoint-initdb.d
    command:
      --server-id=1
      --log-bin=mysql-bin
      --binlog-format=ROW
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
      --default-authentication-plugin=mysql_native_password

  mysql-slave:
    image: mysql:8.0
    container_name: rf-mysql-slave
    restart: always
    ports:
      - "3311:3306"
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: read-fast
    volumes:
      - rf-mysql-slave-data:/var/lib/mysql
      - ./mysql/init/slave:/docker-entrypoint-initdb.d
    command:
      --server-id=2
      --relay-log=relay-log
      --read-only=1
      --log-bin=mysql-bin
      --binlog-format=ROW
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
      --default-authentication-plugin=mysql_native_password

  pmm-server:
    image: percona/pmm-server:2
    container_name: pmm-server
    restart: always
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      - pmm-server-data:/srv
    environment:
      - DISABLE_UPDATES=true
  pmm-client:
    image: percona/pmm-client:2
    container_name: pmm-client
    restart: always
    depends_on:
      - pmm-server
      - mysql
      - mysql-slave
    environment:
      - PMM_AGENT_SERVER_ADDRESS=pmm-server:443
      - PMM_AGENT_SERVER_USERNAME=admin
      - PMM_AGENT_SERVER_PASSWORD=admin
      - PMM_AGENT_SERVER_INSECURE_TLS=1
    volumes:
      - pmm-client-data:/usr/local/percona/pmm2


volumes:
  rf-mysql-data:
  rf-mysql-slave-data:
  pmm-server-data:
  pmm-client-data:
